
# app/domain/conversations/ports.py
from __future__ import annotations

from datetime import timedelta
from typing import Protocol
from uuid import UUID

from app.conversations.models import Conversation, Message, MessageRole

class ConversationRepositoryPort(Protocol):
    async def create(self, owner_id: str, namespace_id: str) -> Conversation: ...
    async def get(self, conversation_id: UUID) -> Conversation | None: ...
    async def list_by_owner(self, owner_id: str) -> list[Conversation]: ...
    async def set_name_and_activate(self, conversation_id: UUID, name: str) -> Conversation: ...
    async def increment_message_count(self, conversation_id: UUID) -> int: ...
    async def delete(self, conversation_id: UUID) -> None: ...
    async def list_stale_drafts(self, older_than: timedelta) -> list[Conversation]: ...


class MessageRepositoryPort(Protocol):
    async def add_message(self, conversation_id: UUID, role: MessageRole, content: str) -> Message: ...
    async def list_messages(self, conversation_id: UUID) -> list[Message]: ...


class ConversationNamerPort(Protocol):
    async def predict_name(self, first_message: str) -> str: ...